version: '3'
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672" # RabbitMQ main port
      - "15672:15672" # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: juscilan
      RABBITMQ_DEFAULT_PASS: pjuscilan
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
